version: 2.1

jobs:
  build-storybook:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build Storybook
          command: npm run build-storybook
      - persist_to_workspace:
          root: .
          paths:
            - storybook-static

  run-interaction-tests:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json"}}
      - run:
          name: install dependencies
          command: npm ci
      - attach_workspace:
          at: .
      - run:
          name: Start Storybook
          command: nohup npx serve -s storybook-static -1 6006 > storybook.log 2>&1 &
      - run:
          name: Wait for storybook to be available
          command: npx wait-on http://localhost:6006
      - run:
          name: Verify storybook is running
          command: curl -I http://localhost:6006 || (echo "Storybook did not start" && exit 1)
      - run:
          name: Run Storybook interaction tests
          command: npm run test-storybooks

workflows:
  version: 2
  test_and_build:
    jobs:
      - build-storybook
      - run-interaction-tests:
          requires:
            - build-storybook