version: 2.1

jobs:
  build-storybook:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: node-deps-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - run:
          name: Build Storybook
          command: npm run build-storybook
      - persist_to_workspace:
          root: .
          paths:
            - storybook-static

  run-interaction-tests:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json"}}
      - run:
          name: install dependencies
          command: npm ci
      - attach_workspace:
          at: .
      - run:
          name: Start Storybook
          command: npx storybook dev -p 6006 --host 0.0.0.0
          background: true
      - run: 
          name: Install Playwright
          command: npx playwright install --with-deps
      - run:
          name: Run Storybook interaction tests
          command: npm run test-storybook

  publish-to-chromatic:
    docker:
      - image: cimg/node:20.10
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-deps-{{ checksum "package-lock.json" }}
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Publish Storybook to Chromatic
          command: npx chromatic --project-token=$CHROMATIC_PROJECT_TOKEN

workflows:
  version: 2
  test_and_build:
    jobs:
      - build-storybook
      - run-interaction-tests:
          requires:
            - build-storybook
      - publish-to-chromatic:
          requires:
            - run-interaction-tests